all: UD_German-HDT UD_German-GSD UD_German-LIT

UD_German-HDT:
	git clone https://github.com/UniversalDependencies/UD_German-HDT.git

UD_German-GSD:
	git clone https://github.com/UniversalDependencies/UD_German-GSD.git

UD_German-LIT:
	git clone https://github.com/UniversalDependencies/UD_German-LIT.git
