all:
	wget -nc https://raw.githubusercontent.com/acoli-repo/acoli-corpora/master/external/enhgcorpus/penn/16.1/Septembertestament-Acts.ref
	wget -nc https://raw.githubusercontent.com/acoli-repo/acoli-corpora/master/external/enhgcorpus/penn/16.1/Septembertestament-John.ref
	wget -nc https://raw.githubusercontent.com/acoli-repo/acoli-corpora/master/external/enhgcorpus/penn/16.1/Septembertestament-Mark.ref
	wget -nc https://raw.githubusercontent.com/acoli-repo/acoli-corpora/master/external/enhgcorpus/penn/16.1/Septembertestament-Matthew.ref
	wget -nc https://raw.githubusercontent.com/acoli-repo/acoli-corpora/master/external/enhgcorpus/README.md
