all: tiger-xml

tiger-xml:
	mkdir tiger-xml
	wget https://www.laudatio-repository.org/download/format/12/23/1.1 -O tiger-xml/Mercurius.tiger.zip
	unzip tiger-xml/Mercurius.tiger.zip
	cd tiger-xml;\
	unzip -u *1-1.zip;\
	rm *.zip
